### ISSUE TITLE
.. Error while starting appdaemon3[request]

### ISSUE THREAD

**Issue by sumitrajancse** [hassio-addons/addon-appdaemon3#1]
# Problem/Motivation
Installed the addon and there is error in the logs and dashboard does not show
> (Why the issue was filed)

## Expected behavior
See the dashboard
> (What you expected to happen)

## Actual behavior

> (What actually happened)
Nothing .. Appdaemon not found

   "description": "Python Apps and HADashboard using AppDaemon 3.x for Home Assistant",
      "state": "started",
      "version": "0.1.0",
      "installed": "0.1.0",
      "repository": "a0d7b954",
      "icon": true,
      "logo": true
    }
  ],
  "addons_repositories": [
    "https://github.com/hassio-addons/repository"
  ]
} .version
DEBUG: Current Supervisor version: 0.85
DEBUG: Supervisor version condition: >=0.85.0
INFO: Supervisor version requirements checks passed.
[cont-init.d] 03-version-requirements.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
TRACE: hass.directory_exists: /config/appdaemon
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-compiled-dir.sh: executing... 
[cont-init.d] 21-compiled-dir.sh: exited 0.
[cont-init.d] 50-compiled-symlink.sh: executing... 
**TRACE: hass.directory_exists: /config/appdaemon/compiled**
[cont-init.d] 50-compiled-symlink.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
TRACE: hass.config.has_value: system_packages
TRACE: hass.jq.has_value: /data/options.json .system_packages
TRACE: hass.jq: /data/options.json .system_packages | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-python-packages.sh: executing... 
TRACE: hass.config.has_value: python_packages
TRACE: hass.jq.has_value: /data/options.json .python_packages
TRACE: hass.jq: /data/options.json .python_packages | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
[cont-init.d] 81-python-packages.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
starting version 3.2.4
[services.d] done.
TRACE: hass.config.get: log_level
TRACE: hass.config.exists: log_level
TRACE: hass.jq.exists: /data/options.json .log_level
TRACE: hass.jq: /data/options.json .log_level
TRACE: hass.jq.is_string: /data/options.json .log_level
TRACE: hass.jq.is: /data/options.json .log_level string
TRACE: hass.jq: /data/options.json .log_level | if type=="string" then true else false end
TRACE: hass.jq: /data/options.json .log_level // empty
TRACE: hass.string.lower: trace
**ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml**
TRACE: hass.config.get: log_level
TRACE: hass.config.exists: log_level
TRACE: hass.jq.exists: /data/options.json .log_level
TRACE: hass.jq: /data/options.json .log_level
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please refer to the AppDaemon3 documentation on how to migrate your configuration files.
As stated in the add-on documentation, AppDaemon3 is not backward compatible with AppDaemon2.

**Comment by sumitrajancse** [comment]
I cannot find the migration documentation.. can you please provide the link ?
