### ISSUE TITLE
Oops! Something went wrong - HA Dashboard wont load

### ISSUE THREAD

**Issue by satssehgal** [hassio-addons/addon-appdaemon3#14]
#Problem/Motivation

Cannot load this add -on for some reason. Below is what the log shows:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon3 v1.0.1
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 03-version-requirements.sh: executing... 
Version 103 is not a valid version.Error: "No Major.Minor.Patch elements found"FATAL: You Supervisor version is: 103
FATAL: This add-on requires: >=0.85.0
FATAL: Please consider upgrading.
[cont-init.d] 03-version-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-compiled-symlink.sh: executing... 
[cont-finish.d] 50-compiled-symlink.sh: exited 0.
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

No idea what happened it just stopped working out of no where. Any thoughts guys? Getting a similar issue with the terminal add on. Other addons are working fine.

**Comment by ghost** [comment]
Happening here as well, same versions. I'm guessing this script should be pulling homeassistant version number from the following URL and is instead getting hassio version number

https://raw.githubusercontent.com/home-assistant/hassio/master/version.json

{
    "hassio": "103",
    "homeassistant": "0.68.1",
    "resinos": "1.3",
    "resinhup": "0.3",
    "generic": "0.3",
    "cluster": "0.1"
}

<blockquote></blockquote>

**Comment by satssehgal** [comment]
I think so. Have you found a way to fix it?

 

Looks like Hassio supervisor just updated to 103.1. I can see the dashboard but none of my entities are recognized

**Comment by ghost** [comment]
Nope, after upgrading I'm seeing the same, a bunch of "entity not found" errors.

**Comment by ghost** [comment]
Discussed here:
https://community.home-assistant.io/t/hadashboard-stopped-working/52502/9
https://community.home-assistant.io/t/community-hass-io-add-on-appdaemon3/41261/89

<blockquote><img src="https://community.home-assistant.io/letter_avatar_proxy/v2/letter/s/e47774/200.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/hadashboard-stopped-working/52502/9">HAdashboard stopped working</a></strong></div><div>I am running 103.1 and still see the issue.</div></blockquote>
<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/josephkiser04/200/28909_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-appdaemon3/41261/89">Community Hass.io Add-on: AppDaemon3</a></strong></div><div>Added latitude longitude elevation and timezone to my appdaemon.yaml file and restarted now getting this error.  2018-05-05 19:05:55.417578 WARNING AppDaemon: ------------------------------------------------------------  2018-05-05 19:05:55.440263 WARNING AppDaemon: HASS: Error getting metadata  2018-05-05 19:05:55.441663 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds  2018-05-05 19:06:00.474063 INFO AppDaemon: HASS: Connected to Home Assistant 0.68.1  2018-05-0...</div></blockquote>

**Comment by frenck** [comment]
This issue has been fixed upstream in the Supervisor. Release 103.2 fixes it.

To upgrade:

![](http://g.recordit.co/ZbO5PRMkn1.gif)
