### ISSUE TITLE
HA Dashboard shows cached view

### ISSUE THREAD

**Issue by vks007** [hassio-addons/addon-appdaemon3#17]
# Problem/Motivation

> Hi, I am facing a cache issue with HA Dashboards using AppDaemon. I make changes to the dashboard file with new switches and they dont get reflected as all my browsers cache the previous copy. I have tried 2  desktops and mobile phone , they all show cached data. When I switch to private browsing , I am able to see new changes. Can anyone advise how to avoid this behavior? 

## Expected behavior

> Any changes to the dashboard file should be visible on the browser after a restart of App Daemon.

## Actual behavior

> The browsers keep on showing cached view, I havent cleared the browser cache but I do believe that clearing will solve the issue but that's not the solution I am looking for.

## Steps to reproduce

> Make changes to a dashboard file , say add a new switch. Refresh the dashboard on your browser, it shows a cached view. I am able to reproduce this on my iPhone, desktop chrome & Firefox.

## Proposed changes

> As a workaround , view the same in private mode and you will be able to see the changes.
> describe the rationale behind it)

**Comment by khan3962** [comment]
Depending on what browser you have, this is for chrome: 
The Chrome DevTools can disable the cache.

1.) F12 or Right-click and Inspect Element to open the DevTools.
2.) Now click Network in the toolbar to open the network pane.
3.) Finally, check the Disable cache checkbox at the top.

Keep in mind,this setting is only active while devtools is open. So anytime you are working on your dashboard do that then F5 or the refresh button will load your changes.

**Comment by frenck** [comment]
This add-on does not do any caching itself.
Therefore, this issue should be reported with AppDaemon.
