### ISSUE TITLE
Blank ha_key gets replaced with a key from thin air.

### ISSUE THREAD

**Issue by khan3962** [hassio-addons/addon-appdaemon3#19]
# Problem/Motivation

> (Why the issue was filed)

My dashboards correctly display current state from home assistant so I know they are communicating. However if I try to control anything from the dashboard it doesn't do anything. Upon inspection of home assistant logs I see : [homeassistant.components] homeassistant/turn_on cannot be called without entity_id

appdaemon addon v1.3.0
Home Assistant v0.73.2

(10 hrs later)(I posted this in the appdaemon git incorrectly)
https://github.com/home-assistant/appdaemon/issues/346

I finally got it working again, and have narrowed it down to the ha_key in the configuration being auto set. :
[cont-init.d] 30-auto-password.sh: executing...
INFO: ha_key is missing in the AppDaemon configuration, fixing...
After which the key is set in the conf file, but my HA instance has no key. If I change the ha_url from http://hassio/homeassistant to http://172.17.0.1:8123 (which I got from the HAdashboard v2 addon which worked) and delete ha_key it works again!

## Expected behavior
> (What you expected to happen)

Blank key kept instead of replacing with a key that does not exist

## Actual behavior
> (What actually happened)

ha_key is created/replaced with some random key.

## Steps to reproduce
> (How can someone else make/see it happen)

Have no key in homeassistant.
delete ha_key from appdaemon.yaml or leave it empty
Restart appdaemon addon.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
@khan3962 Could you please tell me which version of the supervisor you are running?

**Comment by frenck** [comment]
Also, could you provide an error log from the Hass.io system panel & add-on logs at the moment things go south? That would be helpful as well.

I suspect another issue is happing here, since the behavoir your are questioning here, is actually the correct behavior. `ha_key` in this case gets an API token from Hass.io and has nothing to do with your HA password.

We are looking into this issue already...

**Comment by khan3962** [comment]
Supervisor 121.
I guess I cant reproduce this issue now...  ha_key is added and control from the dashboards is still available.   I have no idea what was going on then.  I'm closing this issue unless I can reproduce it.  Thanks.
