### ISSUE TITLE
Dashboard updates

### ISSUE THREAD

**Issue by r-jordan** [hassio-addons/addon-appdaemon3#2]
Hi! Great job with the version 3 of Appdaemon but I still have the same problem than version 2.

# Problem/Motivation

The dashboard is not updated when an entity state changes.

## Expected behavior

The state on the dashboard should be updated live when a state change occurs.

## Actual behavior

You don't see the new state until a reload page is done on the browser.

## Steps to reproduce

Changing the state of a switch through the homeassistant interface and then looking to the dashboard state that it's not updated.

## Proposed changes

It's unknown the cause of the problem.

**Comment by frenck** [comment]
Hi @r-jordan,

AppDaemon3 is now out of beta, do you still experience this problem?

If so, could you please provide more information? Like, debug logs, hardware specifications, HA/Hass.io/Supervisor/OS versions?

**Comment by r-jordan** [comment]
Hi Franck,
I've tried again and the problem is still reproducing. But now I know it's
related with the browser used to connect to the dashboard. First I used
Firefox and others. But now I've just tried with chrome and the problem
does not appear again.
