### ISSUE TITLE
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml

### ISSUE THREAD

**Issue by TeckPete** [hassio-addons/addon-appdaemon3#21]
# Problem/Motivation
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml
I had it working and not sure what happened I tried to uninstall then reinstall and nothing.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Did you migrate from AppDaemon X to AppDaemon 3?

**Comment by TeckPete** [comment]
Yes I did.

**Comment by frenck** [comment]
@PETEIOT In that case, the format of the config file has changed. Please refer to the AppDaemon documentation.

The error is not an add-on error, but AppDaemon saying the format of the config file is invalid. 
See this part of the AppDaemon documentation for more information: <https://appdaemon.readthedocs.io/en/latest/#upgrading-from-2-x>

<blockquote><div><strong><a href="https://appdaemon.readthedocs.io/en/latest/#upgrading-from-2-x">Welcome to AppDaemon’s documentation! — AppDaemon 3.0.1 documentation</a></strong></div></blockquote>
