### ISSUE TITLE
enable appdaemon api_port

### ISSUE THREAD

**Issue by engrbm87** [hassio-addons/addon-appdaemon3#24]
# Problem/Motivation
Appdaemon supports api for remote requests but i think the api_port specified in the appdaemon.yaml is not working
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on forwards / enables port 5000, which is also shown in the Hassio add-on interface.

The API is disabled by default, please see the AppDaemon user manual for information on how to activate it: <https://appdaemon.readthedocs.io/en/latest/INSTALL.html#configuration>.

From the add-on perspective, there is not much more I can do, accept forwarding the port. If you still encounter issues with activating and/or using the API, please refer to the upstream project:

https://github.com/home-assistant/appdaemon

<blockquote><div><strong><a href="https://appdaemon.readthedocs.io/en/latest/INSTALL.html#configuration">Installation — AppDaemon 3.0.1 documentation</a></strong></div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/appdaemon">home-assistant/appdaemon</a></strong></div><div>appdaemon - :page_facing_up: Python Apps for Home Assistant</div></blockquote>
