### ISSUE TITLE
Add-On doesn't start when python_packages can't be installed due to missing internet access

### ISSUE THREAD

**Issue by bob1de** [hassio-addons/addon-appdaemon3#26]
# Problem/Motivation

I run hassio as a VM, alongside the firewall. This means that there's no internet connection when hassio boots up and the add-ons are started. Because I use the ``python_packages`` config variable to install third-party packages, the add-on doesn't start at all.

## Expected behavior

The add-on waits until internet connection is available.

## Actual behavior

Package installation is retried 5 times, after which the add-on terminates.

## Steps to reproduce

Add something to ``python_packages``, block the internet connection and start the add-on.

## Proposed changes

Maybe the add-on could be configured in such a way that package installs are retried until there is a working internet connection.

**Comment by bob1de** [comment]
Hm, maybe it would even be better to implement this into the hassio supervisor to allow for restarting any add-on in case it fails.

**Comment by bob1de** [comment]
I now use an automation to start the add-on every minute, however that's not very elegant, because I can't determine why it actually failed, whether that's due to missing internet connection or a broken configuration.

So waiting until packages can be installed seems reasonable to me. Or, even better, is it possible to reuse the installed packages from the last run and only try to upgrade them?

**Comment by frenck** [comment]
Sorry, this is not a feature I'm planning on implementing.
You can check the status of an add-on with the Supervisor if you'd like.
Auto restarting is not a feature that fits into the Docker world.
