### ISSUE TITLE
After upgrade from AD3 1.5 to 1.6, it doesn't work any more

### ISSUE THREAD

**Issue by rpcaeiro** [hassio-addons/addon-appdaemon3#30]
# Problem
The AD service is running, but the Dashboard is not running anymore
No errors
In the appdeamon.yaml I have added the long-lived token generated by the HA

  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      app_dir: /config/appdaemon/apps
      Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJ........

No other error is shown in any of the other log files.
I already checked everything, I don't know what else more I can do.

Thanks
Rui

**Comment by tjorim** [comment]
Change the ha_url and don't use a long-lived access token, the add-on takes care of that.
https://github.com/hassio-addons/addon-appdaemon3/issues/27#issuecomment-435335330
After that restart the add-on and the token should get corrected.

**Comment by rpcaeiro** [comment]
Log of the app:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon v1.6.0
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.10 / HA 0.81.1 / SU 138 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-compiled-dir.sh: executing... 
[cont-init.d] 21-compiled-dir.sh: exited 0.
[cont-init.d] 30-auto-token.sh: executing... 
INFO: Updating Hass.io API token in AppDaemon with the current one...
[cont-init.d] 30-auto-token.sh: exited 0.
[cont-init.d] 31-ha-url.sh: executing... 
[cont-init.d] 31-ha-url.sh: exited 0.
[cont-init.d] 50-compiled-symlink.sh: executing... 
[cont-init.d] 50-compiled-symlink.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-python-packages.sh: executing... 
[cont-init.d] 81-python-packages.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by rpcaeiro** [comment]
Hi tjorim,

Now the config is:
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      app_dir: /config/appdaemon/apps
  dash_url: http://192.168.1.152:5050

I think apps are working but the dash is not. I'm only interested in the dash. No errors are shown.
Thanks
Rui

**Comment by rpcaeiro** [comment]
Solved! The problem was in the version 1.5, that was incorrectly configured and the upgrade went wrong. To solve this, first I had to downgrade it to version 1.5, correct the appdaemon.yaml file and then upgrade again. Before upgrading, make sure the entry ha_key is there. This key is created automatically by the AD. This key is then replaced by a token that will be used from 1.6 on.
