### ISSUE TITLE
Widget_type: Navigate not returning as expected

### ISSUE THREAD

**Issue by DaBIGOne** [hassio-addons/addon-appdaemon3#36]
# Problem/Motivation

I try to navigate to a 2nd dash with a separate skin and then return after an amount of time, for test purposes I've set 3 seconds for now.

in may main dashboard Home.dash I added: 
verlichting:
    widget_type: navigate
    title2: Verlichting
    dashboard: Verlichting
    skin: Verlichting
    args:
        timeout: 3
        return: Home
        skin: Home

## Expected behavior

I expected to go to verlichting.dash with skin Verliching and after 3 seconds to return to Home.dash with Home skin

## Actual behavior

It returned to Home.dash but with Verlichting skin.

## Steps to reproduce

see above

## Proposed changes

I see it takes the arguments into the adressline when navigating to the other dash.
/Verlichting?timeout=3&return=Home&skin=Home&skin=Verlichting
after 3 seconds it returned to:
/Home?skin=Verlichting

somehow the &skin=Home got lost.

When I do not add the skin argument (/Verlichting?timeout=3&return=Home&skin=Verlichting) it still comes back with the verlichting skin to home: /Home?skin=Verlichting

I think this is behaviour is good for keeping the selected skin, but for me every dash needs his own skin.

Maybe it's possible to add a skin variable in the .dash file so it loads with the assigned skin and not with the skin passed in the address bar?

Thanks,

Dennis

**Comment by frenck** [comment]
As I explained on discord, please file an issue with AppDaemon.
