### ISSUE TITLE
Can't install on Pi3

### ISSUE THREAD

**Issue by Notrial** [hassio-addons/addon-appdaemon3#37]
# Problem/Motivation

Can't install the addon on Rasbperry Pi3, latest HassOS, latest Hass.io

## Expected behavior

Installation :)

## Actual behavior

First time HA crashed (required pulling the plug).
Second time it gave an error in HassOS log.

`19-03-29 08:44:18 INFO (SyncWorker_4) [hassio.docker.interface] Pull image hassioaddons/appdaemon3-armhf tag 1.7.0.
19-03-29 08:45:06 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install hassioaddons/appdaemon3-armhf:1.7.0 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").`

## Steps to reproduce

Simply installing the addon.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with Hassio.
Please report this @ https://github.com/home-assistant/hassio

Thanks 👍 

<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio">home-assistant/hassio</a></strong></div><div>:house_with_garden: First private cloud supervisor for home automation - home-assistant/hassio</div></blockquote>
