### ISSUE TITLE
 EX_OK: unbound variable - disable_auto_token 

### ISSUE THREAD

**Issue by schabert** [hassio-addons/addon-appdaemon3#38]
# Problem/Motivation

``` log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.10  (armv7 / raspberrypi3)
 Home Assistant version: 0.90.2
 Supervisor version: 150
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-compiled-dir.sh: executing... 
[cont-init.d] 21-compiled-dir.sh: exited 0.
[cont-init.d] 30-auto-token.sh: executing... 
[00:22:14] INFO: Automatic update of Home Assistant token is disabled.
/var/run/s6/etc/cont-init.d/30-auto-token.sh: line 11: EX_OK: unbound variable
[cont-init.d] 30-auto-token.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 50-compiled-symlink.sh: executing... 
[cont-finish.d] 50-compiled-symlink.sh: exited 0.
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
> (Why the issue was filed)

## Expected behavior

30-auto-token.sh exit with 0
> (What you expected to happen)

## Actual behavior
30-auto-token.sh exit with 1
> (What actually happened)

## Steps to reproduce
config.json
``` code
{
  "disable_auto_token": true,
  "system_packages": [],
  "python_packages": [],
  "log_level": "info"
}
```
start the addon
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Thanks for reporting @schabert, will check right away.

**Comment by frenck** [comment]
Ooops! Sorry @schabert, that should not have happened.

I've applied a fix on the development branch and awaiting builds.
Once they pass, I'll put out a patch release right after.

**Comment by schabert** [comment]
@frenck  that was fast 👏

**Comment by schabert** [comment]
@frenck  only the new version tag is missing

**Comment by frenck** [comment]
@schabert Be patient ;)
I was awaiting the dev build to pass, before tagging ;)

**Comment by frenck** [comment]
@schabert Tagged as v2.0.1

Release process has started, you can follow it here:

<https://gitlab.com/hassio-addons/addon-appdaemon3/pipelines/54695494>

If all is green, refresh your add-on store to make the upgrade show up.

<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/hassio-addons/addon-appdaemon3/pipelines/54695494">Pipeline · Community Hass.io Add-ons / addon-appdaemon3</a></strong></div><div>AppDaemon3 - Community Hass.io Add-on for Home Assistant</div></blockquote>

**Comment by frenck** [comment]
Thanks for the coffee @schabert! That is appreciated! 👍 ☕️
