### ISSUE TITLE
get_state() no longer returns a entity attribute

### ISSUE THREAD

**Issue by mannerisms** [hassio-addons/addon-appdaemon3#4]
# Problem/Motivation
One of my functions that used to work under appdaemon2 returns the following error:
```
his2 = self.get_state("appdaemon.last_motion", 'history_1')
TypeError: get_state() takes from 1 to 2 positional arguments but 3 were given
```

## Expected behavior

return the value of attribute "history_2"

## Actual behavior

TypeError is thrown

## Steps to reproduce

invoke a get_state() for an attribute value

**Comment by frenck** [comment]
Hi There,

This seems like an AppDaemon specific/related thing and not specific to the add-on (which simply installs AppDaemon for you).

You'd probably have more success on the forums or discord chat for this kind of questions.
