### ISSUE TITLE
Jpg NOT Gif

### ISSUE THREAD

**Issue by waynerigley** [hassio-addons/addon-appdaemon3#46]
# Problem/Motivation
After update to 3.0.1 my Dash will NOT show GIF's but still shows JPG
> (Why the issue was filed)

## Expected behavior
Prev to upgrade my dashboard has a 7 day weather (JPG) and a Weather Radar (GIF) that would jump between
> (What you expected to happen)

## Actual behavior
7 Day weather shows, but Radar now just shows blank, testing url and is working
> (What actually happened)

## Steps to reproduce
weather2_frame:
    widget_type: iframe
    title: Weather
    refresh: 15
    img_list:
        - https://icons.wxug.com/data/weather-maps/radar/united-states/cadillac-michigan-region-current-radar-animation.gif
        - https://media.fox2detroit.com/media.fox2detroit.com/weather/images/7day_forecast.jpg
> (How can someone else make/see it happen)

## Proposed changes
not sure
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is out of scope for the add-on, please report this issue with AppDaemon itself. Thanks.
