### ISSUE TITLE
!secret removed from config file when updating

### ISSUE THREAD

**Issue by Beachviolence** [hassio-addons/addon-appdaemon3#47]
# Problem/Motivation

> Keeps removing !secret from my appdaemon config file when updating the addon or hassio

## Expected behavior

> the !secret annotation stays in the config

## Actual behavior

> it removes `!secret` from `!secret token`

**Comment by frenck** [comment]
Please read the documentation.

https://github.com/hassio-addons/addon-appdaemon3#option-disable_auto_token

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-appdaemon3">hassio-addons/addon-appdaemon3</a></strong></div><div>AppDaemon3 - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-appdaemon3</div></blockquote>
