### ISSUE TITLE
cant change Host network port for  the web interface

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-appdaemon3#48]
# Problem/Motivation

while chasing a problem with hadasboard , i have identified that the problem was related to overlapping ports between traccar and appdaemon .
by changing apdaemon host port to 6050  didnt solve the problem , so started to scan my ports and realize that appdaemon was not opening 6050 , it seams that  changing the port on the config interface is not changing the port internally (?).

if first starting traccar , appdaemon wont even start.

when stopping traccar and then first starting appdaemon , the dashboards returned to work as normal, and also traccar seams to work fine .

So starting order of these two addons seams to matter in my case.

so in the end what i did was to load appdaemon on start , and leave traccar for manual start  later .

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
It can be changed via the "Network Config" section in the add-on configuration of the Hass.io panel.
Leave the port as is in the AppDaemon config.

**Comment by gnkarn** [comment]
yes Frenck , what i was saying is that even changing the "network config"  it doesn't really change ( doesn't  take effect after changing and restarting) .

**Comment by frenck** [comment]
Just tested with the v4.0.0 release of the add-on:

![image](https://user-images.githubusercontent.com/195327/60683370-b8409000-9e97-11e9-8c87-fc9ae4372b86.png)

![image](https://user-images.githubusercontent.com/195327/60683363-af4fbe80-9e97-11e9-84c8-1801a95a2b42.png)

![image](https://user-images.githubusercontent.com/195327/60683346-a232cf80-9e97-11e9-9d14-c9617fdff74d.png)

**Comment by gnkarn** [comment]
absolutletly  right, i stopped traccar, and it works fine , i do not understand the conflicts with tracccar , couldn't make it to take less ports , there is not direct mention about it on the traccar config page , it only mentions the normal ports , so  it would use 2 ports not 180 ..
