### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by thundergreen** [hassio-addons/addon-appdaemon3#49]
# Problem/Motivation
I use a custom component which uses emoji 

this would be the fix

https://github.com/home-assistant/appdaemon/pull/417/files

this is my issue for my custom component:

https://github.com/benleb/ad-batterycheck/issues/1

Would be nice if someone could take care of this :)

Thanks in advance guys.. You are the best!
> (Why the issue was filed)

## Expected behavior
Emoji support
> (What you expected to happen)

## Actual behavior
nemoji support
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><img src="https://avatars1.githubusercontent.com/u/512997?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/appdaemon/pull/417">Gimme back the emoji! by benleb · Pull Request #417 · home-assistant/appdaemon</a></strong></div><div>Just kidding... This adds a switch to disable the encoding of every log message to ascii. As someone (a german for example) might want to log &quot;Umlaute&quot; (äöü). Also useful if you want to p...</div></blockquote>

**Comment by frenck** [comment]
This is not how that works.
If AppDaemon does a release, the add-on updates automatically.
