### ISSUE TITLE
ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml

### ISSUE THREAD

**Issue by mpgoebel** [hassio-addons/addon-appdaemon3#5]
# Problem/Motivation

Add-on does not start correctly, throws error ERROR no 'appdaemon' section in /config/appdaemon/appdaemon.yaml

## Expected behavior

Add-on to start without error

## Actual behavior

Add-on starts with error even after uninstall and reinstall, I did configure the appdaemon.yaml file and it error'd with both with and without the updated config.

**Comment by frenck** [comment]
Your appdaemon.yaml is still in AppDaemon2 format, please migrate or delete the "old" configuration files (the add-on will create new ones on start).
