### ISSUE TITLE
System package curl-dev cannot install

### ISSUE THREAD

**Issue by mikaelgz5** [hassio-addons/addon-appdaemon3#50]
# Problem/Motivation

> (Why the issue was filed)
Using system package curl-dev causing Appdaemon not to start 
## Expected behavior
> (What you expected to happen)
Appdaemon to start normally. 

## Actual behavior
> (What actually happened)
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[06:55:52] INFO: Updating Hass.io API token in AppDaemon with the current one...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.10.2-46-gbb3e7ac09b [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.2-42-g95d37f7648 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
v20190809-2683-gfa1dd17543 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20190809-2698-g6ac0abb933 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v20190809-2697-g10ebdda859 [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 25342 distinct packages available
ERROR: unsatisfiable constraints:
  libcrypto1.1-1.1.1c-r0:
    breaks: openssl-dev-1.1.1d-r0[libcrypto1.1=1.1.1d-r0]
    satisfies: world[libcrypto1.1=1.1.1c-r0]
               ca-certificates-20190108-r0[so:libcrypto.so.1.1]
               python3-3.7.3-r0[so:libcrypto.so.1.1]
               libcurl-7.65.1-r0[so:libcrypto.so.1.1]
               apk-tools-2.10.4-r2[so:libcrypto.so.1.1]
               libssl1.1-1.1.1c-r0[so:libcrypto.so.1.1]
               libtls-standalone-2.9.1-r0[so:libcrypto.so.1.1]
  libssl1.1-1.1.1c-r0:
    breaks: openssl-dev-1.1.1d-r0[libssl1.1=1.1.1d-r0]
    satisfies: world[libssl1.1=1.1.1c-r0]
               python3-3.7.3-r0[so:libssl.so.1.1]
               libcurl-7.65.1-r0[so:libssl.so.1.1]
               apk-tools-2.10.4-r2[so:libssl.so.1.1]
               libtls-standalone-2.9.1-r0[so:libssl.so.1.1]
[06:55:55] FATAL: Failed installing package curl-dev
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 

## Steps to reproduce

> (How can someone else make/see it happen)
Adding curl-dev in system package.
{
  "disable_auto_token": false,
  "system_packages": [
    "curl-dev"
  ],
  "python_packages": [],
  "log_level": "info"
}
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by alex-savin** [comment]
Same here
```
root@a0d7b954-appdaemon3.local.hass.io:/$ apk add postgresql-dev
ERROR: unsatisfiable constraints:
  libssl1.1-1.1.1c-r0:
    breaks: openssl-dev-1.1.1d-r0[libssl1.1=1.1.1d-r0]
    satisfies: world[libssl1.1=1.1.1c-r0] python3-3.7.3-r0[so:libssl.so.1.1] libldap-2.4.48-r0[so:libssl.so.1.1] libpq-11.5-r1[so:libssl.so.1.1] libcurl-7.65.1-r0[so:libssl.so.1.1]
               apk-tools-2.10.4-r2[so:libssl.so.1.1] libtls-standalone-2.9.1-r0[so:libssl.so.1.1]
```

**Comment by alex-savin** [comment]
To get it working I was needed to remove package `libcrypto1.1=1.1.1d-r0`
`apk del libcrypto1.1`
then
`apk update`
and after
`apk add postgresql-dev` and `s6-svc -h /var/run/s6/services/appdaemon/`

and only after all these steps all the packages were upgraded and postgresql-dev was installed

**Comment by mikaelgz5** [comment]
Ah, I had to delete libcrypto1.1.
apk del libcrypto1.1
and then
apk add curl-dev

...profit

**Comment by alex-savin** [comment]
@mikaelgz5 But it should be fixed in the base image
That is happened because of the version at the image is libssl1.1-1.1.1c-r0, but all the packages depends on libssl1.1-1.1.1d-r0

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-base/commit/8b27711f577cd7ec386b0312f3a77eefeb1a094b

You need to wait for a new release with a base image update.

**Comment by sinclairpaul** [comment]
Release v4.1.0 updates libcrypto/libssl as per the updated base image.
