### ISSUE TITLE
Update mdi icons to 4.4.95 same as current HA 0.99.2

### ISSUE THREAD

**Issue by jotacor** [hassio-addons/addon-appdaemon3#52]
# Problem/Motivation

AppDaemon doesn't have the same version mdi icons as Home Assistant.
MDI icons version currently in 4.4.95 for HA 0.99.2.

## Expected behavior

Show the same icons as configured in HA.

## Actual behavior

It shows blank.

## Steps to reproduce

Cover device class shutter in HA the default icon is mdi-window-shutter
It doesn't exist in AppDaemon.

## Proposed changes

Update the mdi icons to 4.4.95.

**Comment by sinclairpaul** [comment]
The addon itself can't change this, you would need to log the issue at https://github.com/home-assistant/appdaemon



<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/appdaemon">home-assistant/appdaemon</a></strong></div><div>:page_facing_up: Python Apps for Home Automation. Contribute to home-assistant/appdaemon development by creating an account on GitHub.</div></blockquote>
