### ISSUE TITLE
Install AppDaemon 4 beta instructions

### ISSUE THREAD

**Issue by basnijholt** [hassio-addons/addon-appdaemon3#56]
Edit: I'll keep and update the instructions [here](https://github.com/basnijholt/home-assistant-config/blob/master/appdaemon/hassio_appdaemon4_beta_installation_instructions.md).

**Comment by sinclairpaul** [comment]
I personally wouldn't recommend this, and would wait for the addon to be updated, but do you want to close your issue then?
