### ISSUE TITLE
I can’t get it to start if says main [ERRO] Asked to process document index 0 but there are only 0 document(s)

### ISSUE THREAD

**Issue by Skaveny** [hassio-addons/addon-appdaemon3#57]
I’m trying to get it to start up but I only get a error
I have made a screenshot of the log and in the picture you can also see system information

![2862E88A-9A32-4084-9D33-3C38A5AEE260](https://user-images.githubusercontent.com/1252745/71083832-3b2e7c00-2194-11ea-9685-392b9d9be190.jpeg)

**Comment by frenck** [comment]
Look like an issue with the appdaemon.yaml. Try moving the `appdaemon` folder away (or rename) and restart the add-on and see if it comes up with the default settings.

**Comment by Skaveny** [comment]
Okay I’m going to test it now

**Comment by Skaveny** [comment]
It is working now I removed the folder appdaemon and started it agen and now it’s working thank you for the help:).

i wish you a merry christmas and a happy new year

**Comment by frenck** [comment]
Merry Christmas, a Happy New Year and a healthy new decade!
