### ISSUE TITLE
FATAL: Failed installing package curl-dev

### ISSUE THREAD

**Issue by fregattegit** [hassio-addons/addon-appdaemon3#58]
# Problem/Motivation
Using system package curl-dev causing Appdaemon not to start
> (Why the issue was filed)
to get it started
## Expected behavior
start normal
> (What you expected to happen)
would be very nice to get a hint / a solution
## Actual behavior
my config

{
  "disable_auto_token": false,
  "system_packages": [
    "libcurl",
    "python3",
    "python3-dev",
    "curl-dev",
    "gcc",
    "g++"
  ],
  "python_packages": [
    "hass-apps",
    "pip==19.2.3",
    "pycurl",
    "bluepy==1.3.0"
  ]
}
> (What actually happened)
LOG:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: AppDaemon
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.1.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.103.3
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[22:16:06] INFO: Updating Hass.io API token in AppDaemon with the current one...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.10.3-114-ga27739f065 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.3-110-g913c88060d [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
v20191219-394-ge993a59437 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20191219-398-g4846b3fec5 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v20191219-390-gb1607cc1ff [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 25705 distinct packages available
OK: 76 MiB in 33 packages
OK: 76 MiB in 33 packages
(1/3) Upgrading python3 (3.7.3-r0 -> 3.7.5-r1)
(2/3) Installing pkgconf (1.6.1-r1)
(3/3) Installing python3-dev (3.7.5-r1)
Executing busybox-1.30.1-r2.trigger
OK: 122 MiB in 35 packages
ERROR: unsatisfiable constraints:
  libcrypto1.1-1.1.1d-r0:
    breaks: openssl-dev-1.1.1d-r2[libcrypto1.1=1.1.1d-r2]
    satisfies: world[libcrypto1.1=1.1.1d-r0]
               ca-certificates-20190108-r0[so:libcrypto.so.1.1]
               python3-3.7.5-r1[so:libcrypto.so.1.1]
               libcurl-7.66.0-r0[so:libcrypto.so.1.1]
               apk-tools-2.10.4-r2[so:libcrypto.so.1.1]
               libssl1.1-1.1.1d-r0[so:libcrypto.so.1.1]
               libtls-standalone-2.9.1-r0[so:libcrypto.so.1.1]
  libssl1.1-1.1.1d-r0:
    breaks: openssl-dev-1.1.1d-r2[libssl1.1=1.1.1d-r2]
    satisfies: world[libssl1.1=1.1.1d-r0]
               python3-3.7.5-r1[so:libssl.so.1.1]
               libcurl-7.66.0-r0[so:libssl.so.1.1]
               apk-tools-2.10.4-r2[so:libssl.so.1.1]
               libtls-standalone-2.9.1-r0[so:libssl.so.1.1]
[22:16:15] FATAL: Failed installing package curl-dev
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] appdaemon.sh: executing... 
[cont-finish.d] appdaemon.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
## Steps to reproduce
maybe similar config as mine
> (How can someone else make/see it happen)
see above
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by sinclairpaul** [comment]
Add `libcrypto1.1` and `libssl1.1` to `system_packages` to fix the dependency issue.
