### ISSUE TITLE
FATAL: Failed installing package pycurl

### ISSUE THREAD

**Issue by fregattegit** [hassio-addons/addon-appdaemon3#59]
# Problem/Motivation
tnx for the answer in #58; for some reason pycurl does not start; pip does not get last release
> (Why the issue was filed)
to get appdaemon started
## Expected behavior
to start with these parameters
> (What you expected to happen)

## Actual behavior
my config:

{
  "disable_auto_token": false,
  "system_packages": [
    "libcurl",
    "libcrypto1.1",
    "libssl1.1",
    "python3",
    "python3-dev",
    "gcc",
    "g++"
  ],
  "python_packages": [
    "hass-apps",
    "pycurl",
    "pip==19.3.1",
    "bluepy==1.3.0"
  ]
}
> (What actually happened)
my log:

(8/10) Installing mpc1 (1.1.0-r0)
(9/10) Installing libstdc++ (8.3.0-r0)
(10/10) Installing gcc (8.3.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 208 MiB in 45 packages
(1/3) Installing musl-dev (1.1.22-r3)
(2/3) Installing libc-dev (0.7.1-r0)
(3/3) Installing g++ (8.3.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 274 MiB in 48 packages
Looking in links: https://wheels.hass.io/alpine-3.10/amd64/
Collecting hass-apps
  Downloading https://files.pythonhosted.org/packages/08/23/dd092b2144366057d0ec069ab6bc2c005c5daf546460b300a290f0ba4648/hass_apps-0.20191210.0-py3-none-any.whl (52kB)
Collecting observable>=1.0 (from hass-apps)
  Downloading https://files.pythonhosted.org/packages/45/7c/b4b63f447378e8a0ebcd338d90f9389f57fb23253127425beacf0129edcb/observable-1.0.3-py2.py3-none-any.whl
Requirement already satisfied: voluptuous>=0.11 in /usr/lib/python3.7/site-packages (from hass-apps) (0.11.7)
Requirement already satisfied: appdaemon>=3.0 in /usr/lib/python3.7/site-packages (from hass-apps) (3.0.5)
Collecting cached-property>=1.5.1 (from hass-apps)
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Requirement already satisfied: aiohttp-jinja2==0.15.0 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (0.15.0)
Requirement already satisfied: pyyaml==5.1 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (5.1)
Requirement already satisfied: Jinja2==2.10.1 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (2.10.1)
Requirement already satisfied: daemonize in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (2.5.0)
Requirement already satisfied: sseclient in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (0.0.24)
Requirement already satisfied: bcrypt in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (3.1.7)
Requirement already satisfied: websocket-client in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (0.56.0)
Requirement already satisfied: requests>=2.6.0 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (2.22.0)
Requirement already satisfied: astral in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (1.10.1)
Requirement already satisfied: aiohttp==2.3.10 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (2.3.10)
Requirement already satisfied: feedparser in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (5.2.1)
Requirement already satisfied: yarl==1.1.0 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (1.1.0)
Requirement already satisfied: paho-mqtt in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (1.4.0)
Requirement already satisfied: iso8601 in /usr/lib/python3.7/site-packages (from appdaemon>=3.0->hass-apps) (0.1.12)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.7/site-packages (from Jinja2==2.10.1->appdaemon>=3.0->hass-apps) (1.1.1)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from sseclient->appdaemon>=3.0->hass-apps) (1.12.0)
Requirement already satisfied: cffi>=1.1 in /usr/lib/python3.7/site-packages (from bcrypt->appdaemon>=3.0->hass-apps) (1.12.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->appdaemon>=3.0->hass-apps) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->appdaemon>=3.0->hass-apps) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->appdaemon>=3.0->hass-apps) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->appdaemon>=3.0->hass-apps) (1.25.4)
Requirement already satisfied: pytz in /usr/lib/python3.7/site-packages (from astral->appdaemon>=3.0->hass-apps) (2019.2)
Requirement already satisfied: multidict>=4.0.0 in /usr/lib/python3.7/site-packages (from aiohttp==2.3.10->appdaemon>=3.0->hass-apps) (4.5.2)
Requirement already satisfied: async-timeout>=1.2.0 in /usr/lib/python3.7/site-packages (from aiohttp==2.3.10->appdaemon>=3.0->hass-apps) (3.0.1)
Requirement already satisfied: idna-ssl>=1.0.0 in /usr/lib/python3.7/site-packages (from aiohttp==2.3.10->appdaemon>=3.0->hass-apps) (1.1.0)
Requirement already satisfied: pycparser in /usr/lib/python3.7/site-packages (from cffi>=1.1->bcrypt->appdaemon>=3.0->hass-apps) (2.19)
Installing collected packages: observable, cached-property, hass-apps
Successfully installed cached-property-1.5.1 hass-apps-0.20191210.0 observable-1.0.3
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Looking in links: https://wheels.hass.io/alpine-3.10/amd64/
Collecting pycurl==7.43.0.3
  Downloading https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz (215kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_v1e_5ub/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_v1e_5ub/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-_v1e_5ub/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-_v1e_5ub/pycurl/setup.py", line 229, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_v1e_5ub/pycurl/setup.py", line 944, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-_v1e_5ub/pycurl/setup.py", line 606, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-_v1e_5ub/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-_v1e_5ub/pycurl/setup.py", line 233, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[21:13:11] FATAL: Failed installing package pycurl==7.43.0.3
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] appdaemon.sh: executing... 
[cont-finish.d] appdaemon.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><div><strong><a href="https://wheels.hass.io/alpine-3.10/amd64/">Index of /alpine-3.10/amd64/</a></strong></div></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote><div><strong><a href="https://wheels.hass.io/alpine-3.10/amd64/">Index of /alpine-3.10/amd64/</a></strong></div></blockquote>
<blockquote></blockquote>

**Comment by sinclairpaul** [comment]
I don't fully understand what you are trying to do, however based on your previous issue, the following config works:

`{
  "disable_auto_token": false,
  "system_packages": [
    "libcurl",
    "libcrypto1.1",
    "libssl1.1",
    "python3",
    "python3-dev",
    "curl-dev",
    "gcc",
    "g++"
  ],
  "python_packages": [
    "hass-apps",
    "pip==19.2.3",
    "pycurl",
    "bluepy==1.3.0"
  ]
}`

I would highly recommend seeking out assistance via Discord, rather than logging issues on Github.
