### ISSUE TITLE
Update to AppDaemon 4.0 (non beta) 

### ISSUE THREAD

**Issue by CodeFinder2** [hassio-addons/addon-appdaemon3#61]
# Problem/Motivation
I would like to use an app that requires AD 4.

## Expected behavior

Update the hassio addon to AD v4. 

## Actual behavior

AD v3.0.5 is used.

**Comment by frenck** [comment]
A new add-on will be published for this soon.

**Comment by CodeFinder2** [comment]
Great, thanks! :-)
